apiVersion: batch/v1
kind: Job
metadata:
  name: slack-notify
  namespace: example06
  labels:
    codefresh.io/cert: slack-job
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/sync-wave: "30"
spec:
  template:
    spec:
      containers:
      - name: dummy-message
        image: alpine
        command:
          - "sleep"
          - "3"
      restartPolicy: Never
  backoffLimit: 2    
